### ISSUE TITLE
logging - tags are not printed in "message" field

### ISSUE THREAD

**Issue by Spawek** [el-bart/but#3]
When I want to log 
`
int a = 1, b = 2, c = 3;
loger.info(
    toFieldInfo(a).retag(Tag{std::move(a)}),
    toFieldInfo(b).retag(Tag{std::move(b)}),
    toFieldInfo(c).retag(Tag{std::move(c)}));
`

In json log I receive a "message" field equal "1 2 3" instead of something like "(a: 1), (b: 2), (c: 3)".

**Comment by el-bart** [comment]
thanks for reporting. i've added `VerboseTextConsole` destination, that prints on a screen, in a format similar to the proposed one. it also has a parametrized depth, how far printing should look into a data structure, so that it still remains human-readable. enjoy! :)

**Comment by Spawek** [comment]
thx!
