### ISSUE TITLE
tuple contents being copied on retag

### ISSUE THREAD

**Issue by marcpawl** [el-bart/but#4]
static int copies_made;

struct CopySpy {
  CopySpy() {}
  ~CopySpy() {}
  CopySpy(CopySpy const &) { ++copies_made; }
  CopySpy(CopySpy &&) {}
  CopySpy &operator=(CopySpy const &) {
    ++copies_made;
    return *this;
  }
  CopySpy &operator=(CopySpy &&) = default;
};

CopySpy copy_spy_factory() { return CopySpy(); }

FieldInfo toFieldInfo(CopySpy const &t) {
  using namespace std::string_literals;
  return FieldInfo(Tag("copies_made"s), Value(copies_made));
}

copies_made=0;
CopySpy spy = copy_spy_factory();
auto xxx = std::make_tuple(std::move(t));
ASSERT_EQ(0, copies_made);
auto fi_structured =
          But::Log::Backend::toFieldInfo(xxx);
ASSERT_EQ(0, copies_made);
auto fi_structured =
          But::Log::Backend::toFieldInfo(xxx)..retag(But::Log::Backend::Tag(std::string("data")));;
ASSERT_EQ(0, copies_made); // Will fail

I was trying to create a test case but could not figure out how to execute the test cases within the docker container.

root@0e68226bcef8:/bug/but/build# cmake .. -GNinja
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /bug/but/build
root@0e68226bcef8:/bug/but/build# 

root@0e68226bcef8:/bug/but/build# ninja -t targets
install/strip: phony
install: phony
install/local: phony
list_install_components: phony
edit_cache: phony
rebuild_cache: phony
src/install/strip: phony
src/edit_cache: phony
src/install: phony
src/rebuild_cache: phony
src/list_install_components: phony
src/install/local: phony
libbut.a: phony
build.ninja: RERUN_CMAKE
clean: CLEAN
help: HELP
root@0e68226bcef8:/bug/but/build#

**Comment by marcpawl** [comment]
Version 1.1.0

**Comment by el-bart** [comment]
thanks for the input. in order to run tests you gave to pass `-DBUT_ENABLE_TESTS=ON` to build. see CI scripts (`ci/.build`) for more details/options.

in order to build under docker, just run a container and pass your `PWD` to mount. eg:
```
docker run -it --rm -u $(id -u):$(id -g) -v $PWD:/mnt/src:ro -v $PWD/build:/mnt/build baszerr/but-sdk:v1.1.0
cd /mnt/build
mkdir stuff
cd stuff
cmake -G Ninja  -DBUT_ENABLE_TESTS=ON /mnt/src/
ninja
ctest
```

**Comment by el-bart** [comment]
i've ported the test you have mentioned (original did not compile):
https://github.com/el-bart/but/commit/8718267c77e098af90af1191f65386201baa8a40
it looks to be working as expected.

note that `FieldInfo::retag` is an rvalue member function, so it would not even compile if it was used on an lvalue, that could trigger a copy. LGTM. :)

closing the ticket now. in case i've missed sth here please reopen. :)
